### ISSUE TITLE
Крупный проект по сбору и анализу данных

### ISSUE THREAD

**Issue by dev101** [ils78/linkedin_jobs_parser#1]
Ильшат, мы ищем человека, чтобы реализовать крупный проект по сбору и анализу данных (с сфере недвижимости), на постоянной основе. Если вам интересно - давайте обсудим.

**Comment by ils78** [comment]
Я сейчас взяться за крупный проект не могу ........ ну и  сбор и анализ данных не совсем мой конёк. Поищите лучше кого-нибудь с серьезным опытом в этой области.

**Comment by dev101** [comment]
Крупным проект надо сделать, пока всё только начинается. Под сбором имеется в виду скрейпинг в основном. Анализ - базовый статистический. Сроки и трудозатраты можно обсудить, и это не единоразовый проект, мы ищем человека, который бы занимался этим на постоянной основе. Если не актуально - извините за беспокойство.

**Comment by ils78** [comment]
Что за сайты вы собираетесь мониторить?

**Comment by ils78** [comment]
Какую организацию вы представляете?

**Comment by ils78** [comment]
Предполагается почасовая или фиксированная оплата?

**Comment by dev101** [comment]
Давайте голосом лучше обсудим, дайте какой-нибудь ваш контакт.

**Comment by ils78** [comment]
skype: ilshat.gabdrakhmanov
